version: '3.0'
services:
  php_game:
    build: App
    depends_on:
      - database_game
    container_name: php_game_container
    environment:
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: php -S 0.0.0.0:80
    ports:
      - "8000:80"

  database_game:
    build: DB
    container_name: mysql_game_container
    #image: mysql:8.0
    #restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    expose:
      - '3306'
    volumes:
      - hive_db:/var/lib/mysql

volumes:
  hive_db: